version: '3.8'

services:
  app:
    image: part8-frontend
    build:
      context: ./frontend/
      dockerfile: ./frontend/dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    container_name: part8-frontend-container
    environment:
        - REACT_APP_BACKEND_URL=http://localhost:8000/api/

  server:
    image: part8-backend
    build:
      context: .
      dockerfile: ./backend/dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3001:3001
    container_name: part8-backend-container
    environment:
      - MONGO_URL= #mongo url tähän
  
  reverseproxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
    container_name: reverseproxy-container
    
  #docker-compose -f docker-compose.dev.yml up